version: '3'
services:
  nginx-server:
    image: nginx:1.17.3
    container_name: nginx-api-dev
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
#    ports:
#      - 2000:80
#    depends_on:
#      - jira-server
    network_mode: "host"
    